live_config_reload = true

import = [
   "~/.config/alacritty/tokyo-night.toml"
]


[cursor]
unfocused_hollow = true

[env]

[font]
size = 12.0

[font.italic]
family = "Fira Mono"
style = "Italic"

[font.normal]
family = "Fira Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
#opacity = 0.9
